repos:
  # PYTHON RELATED HOOKS
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-docstring-first
        name: "âœ… Check docstring"
      - id: trailing-whitespace
        name: "âœ… Check trailing whitespace"
      - id: end-of-file-fixer
        name: "âœ… Check end of file"
      - id: check-yaml
        name: "âœ… Check YAML"
      - id: check-ast
        name: "âœ… Check AST"
      - id: debug-statements
        name: "âœ… Check debug statements"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [--fix]
        name: "ğŸ§¹ Lint code with Ruff"
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: "âš« Format code with Black"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        name: "ğŸ† Static type checking using mypy"
        files: datakitchen/
        additional_dependencies: [types-PyYAML, pydantic, types-requests]
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --allow-untyped-globals,
          ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        name: "ğŸ†• Check for code that can use new Python features"
        args: [--py311-plus]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: "ğŸ”’ Check for security issues with Bandit"
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  # should be replaced once ruff supports it: https://github.com/astral-sh/ruff/issues/458
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.3.4
    hooks:
      - id: pydoclint
        name: "ğŸ“ Check docstrings with pydoclint"
        args:
          [
            --style=google,
            --arg-type-hints-in-docstring=False,
            --check-return-types=False,
            --check-yield-types=False,
          ]